### ISSUE TITLE
Not able to use "+" as a key it thinks you are using it between two other keys like "Shift+A"

### ISSUE THREAD

**Issue by TwistedDigits** [dokufreaks/plugin-keyboard#9]
How to recreate: Enter the following:
  `Use the <key>+</key> and <key>-</key> to zoom in and out`
the minus displays properly but the plus does not.

**Comment by Klap-in** [comment]
What would be a manner to distinct between these to functions of the `+` character?

**Comment by Klap-in** [comment]
Hmm, only one plus is not useful for coupling keys, so that should just be displayed as key.

**Comment by LarsGit223** [comment]
Should work now. The only problem existed if the ```+``` is the only character in the ```<key>``` element.

Now, if the content in the ```<key>``` element is only one sign, then it will always be interpreted as a key, not as a separator.

For key combinations the problem is already solved:
If you want to use a combination including the ```+``` you can e.g. use ```<key>ALT-+<key>```.

**Comment by LarsGit223** [comment]
If you want to use a combination including the ```-``` you can e.g. use ```<key>ALT+-</key>```.

**Comment by TwistedDigits** [comment]
Working now, thanks for fixing so quickly! 
Only thing is that although you upped the version, it didn't show up as "Upgradable" in the Extension Manager, but this maybe a cache thing?  I just re-installed and it worked anyway! 
Thanks again!
